services:
  skip:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./prod.env
    environment:
      - PORT=3000
      - SPEED_BASE_URL=https://lookup.checkmycontent.site
      - RUST_LOG=info,tower_http=info
    ports:
      - "3000:3000" 
